name = "nextdrop-cdn"
main = "src/worker.js"
compatibility_date = "2025-01-01"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "ai-content-storage-bucket"

[vars]
ALLOWED_DOMAINS_URL = "https://api.nextdrop.nl/cdn/allowed-domains"

[route]
pattern = "cdn.nextdrop.nl/*"
